dist: trusty

# We don't specify a version because we have an .nvmrc file
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions-using-nvmrc
language: node_js

addons:
  sonarcloud:
    organization: "defra"

env:
  global:
    - DECISION_SERVICE_URL=http://example.com
    - DECISION_SERVICE_USER=admin
    - DECISION_SERVICE_PASSWORD=password
    - CFD_APP=cfd_RuleApp
    - CFD_RULESET=cfd_RuleSet
    - WML_APP=wml_RuleApp
    - WML_RULESET=wml_RuleSet
    - PAS_APP=pas_RuleApp
    - PAS_RULESET=pas_RuleSet

script:
  # Run linting first. No point running the tests if there is a linting issue
  - npm run lint
  # Run unit tests. This will also generate an lcov.info needed to report test
  # coverage to Sonarcloud
  - npm run unit-test
  # Run sonar-scanner which includes uploading the results to SonarCloud
  - sonar-scanner
